server:
  port: 8088
  servlet:
    contextPath: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_api?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

database:
  type: mysql

cache:
  map:
    api:
      name: api