server:
  port: 8088
  servlet:
    contextPath: /

spring:
  datasource:
    url: "@spring.datasource.url@"
    username: "@spring.datasource.username@"
    password: "@spring.datasource.password@"
    driver-class-name: "@spring.datasource.driver-class-name@"

database:
  type: "@database.type@"

cache:
  map:
    api:
      name: api